names = [
    "Adriana",
    "Afonso",
    "Alberto",
    "Aline",
    "Amanda",
    "Ana",
    "Andre",
    "Angela",
    "Antonio",
    "Arthur",
    "Beatriz",
    "Benedito",
    "Bianca",
    "Breno",
    "Bruna",
    "Bruno",
    "Caio",
    "Camila",
    "Carla",
    "Carlos",
    "Carolina",
    "Catarina",
    "Cecilia",
    "Cesar",
    "Clara",
    "Claudio",
    "Cristina",
    "Daniel",
    "Daniela",
    "Debora",
    "Diego",
    "Diogo",
    "Eduarda",
    "Eduardo",
    "Elaine",
    "Elena",
    "Elias",
    "Elisa",
    "Elisabete",
    "Emilia",
    "Enzo",
    "Erica",
    "Fabio",
    "Fatima",
    "Felipe",
    "Fernanda",
    "Fernando",
    "Flavia",
    "Francisco",
    "Gabriel",
    "Gabriela",
    "Giovana",
    "Gustavo",
    "Helena",
    "Henrique",
    "Hugo",
    "Igor",
    "Ines",
    "Isabel",
    "Isabela",
    "Ivan",
    "Joana",
    "Joao",
    "Jorge",
    "Jose",
    "Julia",
    "Juliana",
    "Julio",
    "Larissa",
    "Laura",
    "Leandro",
    "Leonardo",
    "Leticia",
    "Lia",
    "Lorena",
    "Lucas",
    "Lucia",
    "Luciana",
    "Luis",
    "Luisa",
    "Manuel",
    "Marcia",
    "Marcos",
    "Margarida",
    "Maria",
    "Mariana",
    "Mario",
    "Marta",
    "Mateus",
    "Matilde",
    "Miguel",
    "Monica",
    "Natalia",
    "Nelson",
    "Nicolas",
    "Nuno",
    "Olivia",
    "Oscar",
    "Otavio",
    "Patricia",
    "Paula",
    "Paulo",
    "Pedro",
    "Priscila",
    "Rafael",
    "Raquel",
    "Renata",
    "Renato",
    "Ricardo",
    "Rita",
    "Roberto",
    "Rodrigo",
    "Rosa",
    "Samuel",
    "Sandra",
    "Sara",
    "Sergio",
    "Silvia",
    "Sofia",
    "Teresa",
    "Thiago",
    "Tiago",
    "Vanessa",
    "Vera",
    "Vitor",
    "Vitoria",
    "Yasmin",
    "Yuri",
]

worst_name = "Yuri"

def count_steps_find_worst_name(name_list, name_to_find, count=0):
    start = 0
    end = len(name_list) - 1
    
    while start <= end:
        middle = (start + end) // 2

        if name_list[middle] == name_to_find:
            print("Number of iterations: ",count)
            return middle
        
        elif name_list[middle] < name_to_find:
            start = middle + 1
            count +=1    
        else:
            end = middle - 1
            count+=1
    return -1


count_steps_find_worst_name(names, worst_name)
 